### ISSUE TITLE
The action no longer works after the release of surge 0.24

### ISSUE THREAD

**Issue by tbouffard** [adrianjost/actions-surge.sh-teardown#2090]
Hi,
In the workflow of my projects where I use `actions-surge.sh-teardown`, the execution of the action never completes and the workflow execution is canceled after 6 hours.

<details>
<summary>Execution logs with failures</summary>
Sat, 17 Aug 2024 03:02:12 GMT
Run adrianjost/actions-surge.sh-teardown@v1.0.3
Sat, 17 Aug 2024 03:02:23 GMT search for projects that match /[1-9]+ month.? ago/i
Sat, 17 Aug 2024 03:02:23 GMT found 27 projects for teardown
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated 1 month ago)
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 03:02:23 GMT teardown undefined (last updated )
Sat, 17 Aug 2024 09:02:10 GMT Error: The operation was canceled.
</details>

Apparently, the logs produced by surge@0.24 to list deployments are not the same as the logs produced by surge@0.23
In version 0.23, the log for a deployment starts with a timestamp which is no longer present with version 0.24.

The action parse the log of the surge list command (https://github.com/adrianjost/actions-surge.sh-teardown/blob/v1.0.3/index.js#L19-L23), so this is probably the cause of the problem.

0.23 | 0.24
---- | ----
`1717995909830 process-analytics-bpmn-visualization-js-demo_preview-pr-3103.surge.sh   3 weeks ago   surge   surge.sh   Standard` | `process-analytics-bpmn-visualization-js-demo_preview-pr-3103.surge.sh   3 weeks ago   surge   surge.sh   Standard`

**Comment by tbouffard** [comment]
To fix the problem, I see two solution
- Force usage of surge@23 in the npx command. Quick to implement but doesn't prepare the future
- Update the regexp in the parsing code 

If you are interested @adrianjost, I can try to provide a fix on the regexp next week.

**Comment by adrianjost** [comment]
I think I already found a fix. At least locally it worked again. I just can't get my dryrun in CI working. Haven't touched this code for years, so no idea why.

**Comment by adrianjost** [comment]
I think https://github.com/adrianjost/actions-surge.sh-teardown/commit/27d0dc9ab910c2ae46c9389a6f2ca46101ac56a9 should fix the issue.
I just need to get my actions back running to create a release.

**Comment by tbouffard** [comment]
Nice, thanks for the fix. 🏅 
I will check the release once it is available.

**Comment by adrianjost** [comment]
I think I'm a bit stuck here. I can't get the CI to work. Does the action work for you, when you use `uses: adrianjost/actions-surge.sh-teardown@master`?

**Comment by tbouffard** [comment]
I have tested the master branch and this works as expected. 💪🏿 
For more details, see https://github.com/bonitasoft/bonita-documentation-site/issues/771#issuecomment-2304415900

**Comment by adrianjost** [comment]
It's weird that the action works just fine for you, but in my actions it doesn't. 🤷‍♂️
I will create a release for this fix soon. Either manually or by disabling some checks temporarily.

**Comment by adrianjost** [comment]
Not perfect, but at least it's tagged and released: https://github.com/adrianjost/actions-surge.sh-teardown/releases/tag/v1.0.4
